# YAPTIĞIM ÇIKARIMLAR

Builtin 'wave' kütüphanesiyle okunan değerler amplitude yani genliği ifade ediyor. Amplitude yani genlik ne kadar yükselir ise ses o minvalde daha gürültülü oluyor, tam tersi genliğin değeri ne kadar azalır ise de ses o kadar yumuşuyor.
Yapılan convolution işlemi sonucu elimdeki 5snlik ve 10snlik ses dizilerinin değerlerinin pozitif olarak ve aynı zamanda da negatif olarak arttığını gördüm, burada her pozitif değer tam anlamıyla artmayabilir ve negatif değer azalmayabilir. Bunun sebebi de convolution işleminde kullandığım dizinin değerlerinin 0'da 1, 400'de .4 ve 800'de .4 olmasından ötürü, ses dizilerinin değerlerinin farklı pozisyonlarda farklı değerlere sahip olmasıdır. Söz gelimi (1 * 150) + (.4 * -120) + (.4 * -100) gibi durumlar ile karşılaşilabilir ve değerler her zaman pozitif olarak artmayabilir veyahut negatif olarak azalmayabilir.

    Convolution işlemi sonucu elde edilen degerlerdeki negatif ve pozitif değer oranları neredeyse aynı, fakat convolution işlemi elimdeki dizinin eleman sayısını arttırdığı için negatif/pozitif oranı bir nebze bozuluyor.

Elimdeki 5sn ve 10snlik dizilerin genlikleri arttığı için ses daha pozitif yerlerde daha GURULTULU ve negatif oldugu yerlerde daha YUMUSAK çıkıyor fakat genel olarak GÜRÜLTÜnün yani genliğin artmasından dolayı rahatsız edici bir ses oluştuğu için YUMUSAK olmuş olan sesler arada algılanamıyor. 

### Sonuç Olarak
<b> Yaptığım convolution işlemi elimdeki sesleri duyumsal açıdan daha gürültülü bir hale getirmiştir. </b>

<i>Ek açıklamalar ve gösterimler aşağıda mevcuttur.</i>

In [43]:
from convolution import myconv
import wave
import numpy as np
## Open the sounds
with wave.open("5snlik.wav", "r") as sn_5:
    data_sn5 = np.frombuffer(sn_5.readframes(-1), np.int16)
    fs = sn_5.getframerate()
with wave.open("10snlik.wav", "r") as sn_10:
        data_sn10 = np.frombuffer(sn_10.readframes(-1), np.int16) 
    
data_sn5.shape = -1, 2
data_sn5 = data_sn5.T
data_sn5_first_channel = data_sn5[0]

data_sn10.shape = -1, 2
data_sn10 = data_sn10.T
data_sn10_first_channel = data_sn10[0]

SyntaxError: invalid syntax (<ipython-input-43-4a584aad7a24>, line 1)

In [28]:
data_sn5_first_channel

array([179, 184, 162, ..., 182, 175, 145], dtype=int16)

In [29]:
data_sn10_first_channel

array([130, 130,  92, ..., 135, 118, 136], dtype=int16)

In [30]:
Y_function = np.array([1])
Y_function = np.append(Y_function, np.zeros((398)))
Y_function = np.append(Y_function, 0.4)
Y_function = np.append(Y_function, np.zeros(399))
Y_function = np.append(Y_function, 0.4)
My_Y1, _ = myconv(data_sn5_first_channel, 0, Y_function, 0)
Y1 = np.convolve(data_sn5_first_channel, Y_function)
My_Y2, _ = myconv(data_sn10_first_channel, 0, Y_function, 0)
Y2 = np.convolve(data_sn10_first_channel, Y_function)

In [31]:
My_Y2, _ = myconv(data_sn10_first_channel, 0, Y_function, 0)

In [32]:
Y2 = np.convolve(data_sn10_first_channel, Y_function)

## 5snlik Kayit Analizi

In [33]:
My_Y1

array([179. , 184. , 162. , ...,  72.8,  70. ,  58. ])

In [34]:
Y1

array([179. , 184. , 162. , ...,  72.8,  70. ,  58. ])

In [35]:
print("myconv fonksiyonundan elde ettigim arrayin uzunlugu:", len(My_Y1))
print("numpy.convolve fonksiyonundan elde ettigim arrayin uzunlugu:", len(Y1))
print("myconv ve numpy.convolve sonuclari ayni mi: ", any(My_Y1 == Y1))

myconv fonksiyonundan elde ettigim arrayin uzunlugu: 221299
numpy.convolve fonksiyonundan elde ettigim arrayin uzunlugu: 221299
myconv ve numpy.convolve sonuclari ayni mi:  True


In [36]:
print("'Max' deger normal 5snlik kayit:", max(data_sn5_first_channel))
print("'Min' deger normal 5snlik kayit:", min(data_sn5_first_channel))
print("'Ortalama' deger normal 5snlik kayit", np.average(data_sn5_first_channel))
print("'Max' deger convolution 5snlik kayit:", max(Y1))
print("'Min' deger convolution 5nslik kayit:", min(Y1))
print("'Ortalama' deger normal 5snlik kayit",np.average(Y1))

'Max' deger normal 5snlik kayit: 1920
'Min' deger normal 5snlik kayit: -1498
'Ortalama' deger normal 5snlik kayit 141.45156916099774
'Max' deger convolution 5snlik kayit: 2352.2000000000003
'Min' deger convolution 5nslik kayit: -1770.0
'Ortalama' deger normal 5snlik kayit 253.6935449324217


In [37]:
count = 0
count2 = 0
for item in data_sn5_first_channel:
    if item != -item:
        count += 1
for item in Y1:
    if item != -item:
        count2 += 1
        
print(f"normal 5snlik dizide '{count}' kadar negatif deger, {len(data_sn5_first_channel - count)} kadar da pozitif deger mevcut.")
print(f"convolion uygulanan 5snlik dizide '{count2}' kadar negatif deger, {len(Y1 - count2)} kadar da pozitif deger mevcut.")
print(f"Normal dizi oran: {count / (len(data_sn5_first_channel - count))}, \nConvolution islemi yapilan array icin oran: {count2 / (len(Y1 - count2))}")
print("Oranlar ayni mi: {}".format(count / (len(data_sn5_first_channel - count)) == count2 / (len(Y1 - count2))))

normal 5snlik dizide '220372' kadar negatif deger, 220500 kadar da pozitif deger mevcut.
convolion uygulanan 5snlik dizide '221289' kadar negatif deger, 221299 kadar da pozitif deger mevcut.
Normal dizi oran: 0.9994195011337869, 
Convolution islemi yapilan array icin oran: 0.9999548122675656
Oranlar ayni mi: False


## 10snlik Kayit Analizi

In [38]:
My_Y2

array([130. , 130. ,  92. , ...,  54. ,  47.2,  54.4])

In [39]:
Y2

array([130. , 130. ,  92. , ...,  54. ,  47.2,  54.4])

In [40]:
print("myconv fonksiyonundan elde ettigim arrayin uzunlugu:", len(My_Y2))
print("numpy.convolve fonksiyonundan elde ettigim arrayin uzunlugu:", len(Y2))
print("myconv ve numpy.convolve sonuclari ayni mi: ", any(My_Y2 == Y2))

myconv fonksiyonundan elde ettigim arrayin uzunlugu: 441799
numpy.convolve fonksiyonundan elde ettigim arrayin uzunlugu: 441799
myconv ve numpy.convolve sonuclari ayni mi:  True


In [41]:
print("'Max' deger normal 5snlik kayit:", max(data_sn10_first_channel))
print("'Min' deger normal 5snlik kayit:", min(data_sn10_first_channel))
print("'Ortalama' deger normal 10snlik kayit", np.average(data_sn10_first_channel))
print("'Max' deger convolution 10snlik kayit:", max(Y2))
print("'Min' deger convolution 10nslik kayit:", min(Y2))
print("'Ortalama' deger normal 10snlik kayit",np.average(Y2))

'Max' deger normal 5snlik kayit: 6086
'Min' deger normal 5snlik kayit: -5289
'Ortalama' deger normal 10snlik kayit 139.94345124716554
'Max' deger convolution 10snlik kayit: 6125.2
'Min' deger convolution 10nslik kayit: -6207.6
'Ortalama' deger normal 10snlik kayit 251.4426506171359


In [42]:
count = 0
count2 = 0
for item in data_sn10_first_channel:
    if item != -item:
        count += 1
for item in Y2:
    if item != -item:
        count2 += 1
        
print(f"normal 5snlik dizide '{count}' kadar negatif deger, {len(data_sn10_first_channel - count)} kadar da pozitif deger mevcut.")
print(f"convolion uygulanan 5snlik dizide '{count2}' kadar negatif deger, {len(Y2 - count2)} kadar da pozitif deger mevcut.")
print(f"Normal dizi oran: {count / (len(data_sn10_first_channel - count))}, \nConvolution islemi yapilan array icin oran: {count2 / (len(Y1 - count2))}")
print("Oranlar ayni mi: {}".format(count / (len(data_sn10_first_channel - count)) == count2 / (len(Y2 - count2))))

normal 5snlik dizide '440501' kadar negatif deger, 441000 kadar da pozitif deger mevcut.
convolion uygulanan 5snlik dizide '441746' kadar negatif deger, 441799 kadar da pozitif deger mevcut.
Normal dizi oran: 0.9988684807256236, 
Convolution islemi yapilan array icin oran: 1.9961500051965892
Oranlar ayni mi: False
